name: Bug report
description: Create a bug report to assist us in resolving issues with the repository.
title: "[BUG] <bug description>"
labels: [bug]
body:
  - type: textarea
    id: bugdescription
    attributes:
      label: Description of the bug
    validations:
      required: true
  - type: input
    id: stack
    attributes:
      label: Project stack or language (e.g. front-end)
    validations:
      required: true
  - type: textarea
    id: workingenvironment
    attributes:
      label: Working Environment (e.g. operating system, browser, device)
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Please add screenshots (if applicable)
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add more information about the bug here
    validations:
      required: false
